[package]
edition = "2024"
name = "west"
version = "0.0.1"
authors = ["kkettums"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
dotenv = "0.15.0"
serde_json = "1.0"
